DROP EXTERNAL FUNCTION CSCATEGORY;
DROP EXTERNAL FUNCTION CSCATEGORYCOLOR;
DROP EXTERNAL FUNCTION CSADDSEPARATOR;
DROP EXTERNAL FUNCTION CSADDCHECKPOINT;
DROP EXTERNAL FUNCTION CSCLEAR;
DROP EXTERNAL FUNCTION CSRESETCHECKPOINT;
DROP EXTERNAL FUNCTION CSSENDMEMORYSTATUS;
DROP EXTERNAL FUNCTION CSENABLE;
DROP EXTERNAL FUNCTION CSDISABLE;
DROP EXTERNAL FUNCTION CSENABLED;
DROP EXTERNAL FUNCTION CSDESTINATIONDETAILS;
DROP EXTERNAL FUNCTION CSENTERMETHOD;
DROP EXTERNAL FUNCTION CSEXITMETHOD;
DROP EXTERNAL FUNCTION CSSENDMSG;
DROP EXTERNAL FUNCTION CSSENDSTRING;
DROP EXTERNAL FUNCTION CSSENDINTEGER;
DROP EXTERNAL FUNCTION CSSENDFLOAT;
DROP EXTERNAL FUNCTION CSSENDNOTE;
DROP EXTERNAL FUNCTION CSWRITEINTEGER;
DROP EXTERNAL FUNCTION CSWRITEFLOAT;
DROP EXTERNAL FUNCTION CSWRITESTRING;
DROP EXTERNAL FUNCTION CSWRITEMSG;

drop procedure csCategory;
drop procedure csCategoryColor;
drop procedure csAddSeparator;
drop procedure csAddCheckpoint;
drop procedure csClear;
drop procedure csResetCheckpoint;
drop procedure csSendMemoryStatus;
drop procedure csEnable;
drop procedure csDisable;
drop procedure csEnabled;
drop procedure csDestinationDetails;
drop procedure csEnterMethod;
drop procedure csExitMethod;
drop procedure csSendMsg;
drop procedure csSendString;
drop procedure csSendInteger;
drop procedure csSendFloat;
drop procedure csSendNote;
drop procedure csWriteMsg;
drop procedure csWriteString;
drop procedure csWriteInteger;
drop procedure csWriteFloat;

